package backend.Model;

public enum NotificationType {
    EMERGENCY_ALERT,
    LOW_STOCK,
    APPOINTMENT_REMINDER,
    APPOINTMENT_CONFIRMED,
    APPOINTMENT_CANCELLED,
    DONATION_COMPLETED,
    REQUEST_UPDATE,
    ELIGIBILITY_UPDATE,
    BLOOD_REQUEST_URGENT,
    GENERAL
}
